#!/usr/bin/env python3
"""
Generate 《两只老虎》MP3 using pydub
"""

import math
from pydub import AudioSegment
from pydub.generators import Sine

# Note frequencies (in Hz) - C major scale starting at C4
NOTE_FREQS = {
    'C4': 261.63,
    'D4': 293.66,
    'E4': 329.63,
    'F4': 349.23,
    'G4': 392.00,
    'A4': 440.00,
    'B4': 493.88,
    'C5': 523.25,
    'D5': 587.33,
    'G3': 196.00,
}

# Melody of 《两只老虎》(Two Tigers)
# Each tuple: (note, duration_in_ms, delay_after_note_in_ms)
MELODY = [
    # 两只老虎，两只老虎
    ('C4', 300, 50), ('D4', 300, 50), ('E4', 300, 50), ('C4', 400, 200),
    ('C4', 300, 50), ('D4', 300, 50), ('E4', 300, 50), ('C4', 400, 200),
    # 跑得快，跑得快
    ('E4', 300, 50), ('F4', 300, 50), ('G4', 500, 300),
    ('E4', 300, 50), ('F4', 300, 50), ('G4', 500, 300),
    # 一只没有耳朵，一只没有尾巴
    ('G4', 150, 50), ('A4', 150, 50), ('G4', 150, 50), ('F4', 150, 50), ('E4', 300, 50), ('C4', 400, 200),
    ('G4', 150, 50), ('A4', 150, 50), ('G4', 150, 50), ('F4', 150, 50), ('E4', 300, 50), ('C4', 400, 200),
    # 真奇怪，真奇怪
    ('C4', 300, 50), ('G3', 300, 50), ('C4', 600, 300),
    ('C4', 300, 50), ('G3', 300, 50), ('C4', 600, 400),
]

def generate_note(frequency, duration_ms, volume=0.3):
    """Generate a sine wave note with fade in/out"""
    # Generate the tone
    tone = Sine(frequency).to_audio_segment(duration=duration_ms)
    # Apply volume
    tone = tone - (20 - 20 * volume)  # Convert to dB attenuation
    # Apply short fade to avoid clicking
    fade_duration = min(50, duration_ms // 4)
    tone = tone.fade_in(fade_duration).fade_out(fade_duration)
    return tone

def generate_silence(duration_ms):
    """Generate silence"""
    return AudioSegment.silent(duration=duration_ms)

def generate_song():
    """Generate the full song as AudioSegment"""
    song = AudioSegment.empty()
    
    for note_name, duration, delay in MELODY:
        if note_name in NOTE_FREQS:
            # Generate the note
            note = generate_note(NOTE_FREQS[note_name], duration)
            song += note
            # Add delay after note
            song += generate_silence(delay)
    
    return song

def main():
    print("Generating 《两只老虎》...")
    
    try:
        song = generate_song()
        
        # Export as MP3
        output_file = "twotigers.mp3"
        song.export(output_file, format="mp3", tags={
            'title': '两只老虎 (Two Tigers)',
            'artist': 'Generated',
            'comments': 'Generated by Python script'
        })
        
        print(f"Success! MP3 saved to: {output_file}")
        print(f"Duration: {len(song) / 1000:.2f} seconds")
        
    except Exception as e:
        print(f"Error: {e}")
        print("\nNote: This script requires 'pydub'. Install it with:")
        print("  pip install pydub")
        print("Also ensure ffmpeg is installed on your system.")

if __name__ == "__main__":
    main()
